### ISSUE TITLE
Speedup simplify 

### ISSUE THREAD

**Issue by apkunpacker** [CalebFenton/simplify#122]
Simplify working great on simplification of classes given by -it but giving whole dex or apk taking too much time . Is there anything which can speedup simplify at default parameter set ? I would like to suggest a feature request of showing approx predicated time in completing simplification after first calculating number of classes and provided perameter value . If it is possible that would be great help . Thanks

**Comment by CalebFenton** [comment]
Do you have any suggestions on how to accurately predict how long a class will take to analyze? My guess is that problem is itself as difficult as analyzing and simplifying the code.

There are optimizations that could be done. I've only profiled a little, and mostly around register management and item cloning. There's probably a lot of other optimizations that could be done that wouldn't require a massive rewrite of smalivm.

In general, I think the best case would be to fail more gracefully for classes which can't be optimized. You don't have to try very hard to run into the halting problem in almost every non-trivial class.

**Comment by GovindSharma123** [comment]
so only way to speed up the simplification is to target only required class  ?

**Comment by GovindSharma123** [comment]
so only way to speedup simplification is target required class ? 1 more request last simplify build is of 2017 and we still using that because we can not build  . may u build a new one with fix of all bugs appear after last build . thanks
