### ISSUE TITLE
no failed,no error and no optimizations

### ISSUE THREAD

**Issue by njsunsky** [CalebFenton/simplify#133]
hi,my friend ,i use your example,but i get the following message,why no any optimizations
D:\G\simplify>java -jar simplify/build/libs/simplify.jar -it 'org/cf/obfuscated' simplify/obfuscated-app.apk
Simplification complete:
        total classes = 0
        total methods = 0
        optimized methods = 0
        failed methods = 0
        run time = 1334 ms
Total optimizations:

**Comment by CalebFenton** [comment]
Could you run this with verbose mode and include the output?

**Comment by njsunsky** [comment]
thank you for your reply
i don't know how to run this with verbose mode 
accrod your example,you give two files,simplify and smalivm
but i don't know how to use smalivm

**Comment by CalebFenton** [comment]
I spent a lot of time writing up what I thought would be useful information and putting it in the readme. You should check it out. Simplify isn't a point and click tool. You need to know what you're doing and what you want.

Verbose mode is a near universal option in command line interface tools and it's normally `-v`. You can get help from most tools with `-h`. From the readme you can see it clearly:
<img width="907" alt="Screen Shot 2019-10-29 at 1 41 07 PM" src="https://user-images.githubusercontent.com/1356658/67807314-d0917780-fa51-11e9-8e35-b8d57c3a1d68.png">

Verbose in this case is really important because I can't reproduce your issue and verbose gives a lot of detail about what simplify is doing.

I don't know what you mean by giving two files simplify and smalivm. You'll have to be a bit more specific, sorry.

**Comment by njsunsky** [comment]
thank you sir,now, i know how to use verbose mode ,i will keep read your documents,thanks again

**Comment by CalebFenton** [comment]
It could be that you didn't clone recursively. Include verbose logs if you still have trouble.
