### ISSUE TITLE
aput-object should be able to handle items of the same type (specifically classes)

### ISSUE THREAD

**Issue by strazzere** [CalebFenton/simplify#25]
Below is a simplified (oh, my jokes, so good) example of something I'd run across in the wild.

```
.class public Lbreak_aputs_object;
.super Ljava/lang/Object;

.method public static womp()V
    .registers 5

    const/4 v1, 0x2
    new-array v2, v1, [Ljava/lang/Class;

    const/4 v0, 0x0
    sget-object v3, Ljava/lang/Boolean;->TYPE:Ljava/lang/Class;
    aput-object v3, v2, v0

    const/4 v0, 0x1
    const-class v4, Landroid/app/Instrumentation;
    aput-object v4, v2, v0

    return-void
.end method
```

Not that it is creating an array of 2 items of type java/lang/Class, then adds them. So the java-esk code would be;
```
public class breaks_aputs_object {
    public static womp() {
        Class[] classes = new Class[2];
        classes[0] = Boolean.TYPE;
        classes[1] = android.app.Instrumention.class;
    }
}
```

However since Landroid/app/Instrument; is turned into a LocalClass - it is no longer actually a class, resulting in this error;
```
Executing: Lbreak_aputs_object;->womp()V
WARN  MethodExecutor - aput-object r4, r2, r0 generated an exception:
java.lang.IllegalArgumentException: array element type mismatch
	at java.lang.reflect.Array.set(Native Method) ~[na:1.7.0_55]
	at org.cf.smalivm.opcode.APutOp.execute(APutOp.java:86) ~[bin/:na]
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:45) ~[bin/:na]
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:69) ~[bin/:na]
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:111) [bin/:na]
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:92) [bin/:na]
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:88) [bin/:na]
	at org.cf.simplify.Main.main(Main.java:55) [bin/:na]
```

I'm unsure how this should be handled in the current framework/designs.

**Comment by CalebFenton** [comment]
filled-new-array will also need to return this new array type

**Comment by CalebFenton** [comment]
This was a problem because `Class` objects were not available for input and framework Smali classes. Instead of actual JVM Class objects, I was using objects of placeholder classes like `LocalInstance` or `LocalType`. If a `Class[]` array was created, it couldn't hold `LocalType` objects.

The last several commits have added dynamic JVM class generation based on Smali class definitions. This allows smalivm to have actual classes for input and framework smali classes.

I tested this recently against a sample of obad pre-processed with dex-oracle and it optimized the method, for the most part. Woo.
