### ISSUE TITLE
May i get some help?

### ISSUE THREAD

**Issue by Rewtarded** [CalebFenton/simplify#49]
@CalebFenton 
I built the project, made the simplify.jar, tested it and worked. Now what? Do i keep using the simplify.jar or do i have to rebuild it using the files of the apk i want to dobfuscate? if so where do i put the files? Maybe i could get a more detailed explanation on how to work this. Modded kik(Messaging App) applications is a thing.. so the people who created the modded application put what they call an "antiskid" on it. aka obfuscation string encryption. I would like to get pass this so i can see what they did for personal reasons. I have an interest in trying to understand how programming/coding works. I've been researching smali, etc for the past couple of days now. I don't have much background knowledge from education but i can pick up things fast with a will to know how. Would you be so kind to help me.. i'd appreciate it. look at the images i sent.

![capture](https://cloud.githubusercontent.com/assets/20191494/16425395/6b496e8a-3d32-11e6-8378-7fe9075f1889.JPG)
![13](https://cloud.githubusercontent.com/assets/20191494/16425441/ba579966-3d32-11e6-83b4-c1e236fdb9a5.JPG)
![capture2](https://cloud.githubusercontent.com/assets/20191494/16425442/ba5fa764-3d32-11e6-9ef0-a4bbd78c4f76.JPG)

**Comment by CalebFenton** [comment]
hello Rewtarded :D

simplify doesn't need to be rebuilt for each apk. it's self-contained. everything simplify needs to run is contained in the jar you built. there are some configuration files you could modify if you wanted, but it would probably be easier to modify them in the source code repo and rebuild it that way. you'd also have to get way into understanding how simplify works before you'd want to modify any of those.

ahh looks like they cracked it and don't want people to steal their methods. should be fun to reverse. just point simplify at the apk you want to deobfuscate but try limiting it to just a few classes, maybe one class or one method you want to see. but to be sure, simplify is a technically demanding tool. obfuscation is tricky and a general purpose tool is necessarily going to take a little massaging. if you're genuinely curious, i talk more about how it works here: https://calebfenton.github.io/2016/04/30/dalvik-virtual-execution-with-smalivm/

play with simplify and your apk for a while. try and get it to work. if you run into trouble like simplify crashes or have other questions, you can respond here, but at least include the apk file hashes so i can get a copy.

one thing to keep in mind is the deobfuscation won't be able to work if there's certain kinds of state involved in decryption. for example, if the decryption key is downloaded from the internet, read from a file system, or contained in an instance variable, smalivm will not be able to get those values.

**Comment by Rewtarded** [comment]
@CalebFenton 
Hey, thanks for the feedback. I took a look at the link you provided as well as a presentation i found on different types of obfuscation. Unfortunately, as you mentioned in your post, I don't think Simplify is the right tool to use. When i do the entire Smali folder in the apk, simplify shoots out a dex with no problem, but i don't think it's actually doing anything. I can't really tell though because the entire smali folder + resources all have this string encryption..The Japanese Letters really make my head hurt, Lol. There's some type of patten there i'm sure. When i pick a random Smali to try or a single method, it gives me all kinds of errors. I may or may not be using Simplify right.  

However I used simplify against an official version of the Kik Application (With default proGuard i'm assuming) and worked perfectly. I saw how it condensed the Smali code into a more feasible format to read. 

Not sure what my next move is. Would you recommend dex-oracle? I see that there's a plugin for string encryption. It sounds so simple, but i know that I have to customize the plugin after actually figuring out the pattern in the strings.

Also, I'm not sure what you mean't by 'apk file hashes' but here's a link to the actual apk from my google drive that you can download. 

https://drive.google.com/open?id=0BwhSOSdIKPj8dzF0R180aHdZWTQ

You can take a crack at it if you want (not saying you have to). I don't want to burden you with such an irrelevant task. Name's Paul btw.

**Comment by CalebFenton** [comment]
It looks like there could be some bugs. There shouldn't usually be unhandled virtual exceptions, unless the code actually has bugs and throws exceptions and doesn't handle them.

It also looks like there's some trouble resolving an abstract method. Some class implements that interface, but simplify must be getting confused. This looks like normal app code and not part of any tricky deobfuscation.

```$ java -jar build/libs/simplify.jar sandbox/pikekapril.apk -it 'Lkik/pikek/㢨㝘㧎/㜢䕓㹅䍄;->㰛㢕㦊䙕\('                                                                     130 ↵
Executing: Lkik/pikek/㢨㝘㧎/㜢䕓㹅䍄;->㰛㢕㦊䙕(Ljava/lang/Object;)V
13:37:31.855 ERROR NodeExecutor - ExecutionNode{signature=Lkik/pikek/㢨㝘㧎/㜢䕓㹅䍄;->Go_Learn_Something(Ljava/lang/String;I)Ljava/lang/String;, op=aput-object r1, r0, r7} unhandled virtual exception: Ljava/lang/ArrayStoreException; int
13:37:31.857 WARN  InvokeOp     - Unhandled virtual exception: Ljava/lang/ArrayStoreException; int
13:37:31.909 ERROR NodeExecutor - ExecutionNode{signature=Lkik/pikek/㢨㝘㧎/㜢䕓㹅䍄;->Go_Learn_Something(Ljava/lang/String;I)Ljava/lang/String;, op=aput-object r1, r0, r7} unhandled virtual exception: Ljava/lang/ArrayStoreException; int
13:37:31.909 WARN  InvokeOp     - Unhandled virtual exception: Ljava/lang/ArrayStoreException; int
13:37:31.910 WARN  InvokeOp     - Attempting to execute local method without implementation: Lkik/䀆㚇䭰㛊㨴䏭㸞/䌺䦿䣅/䉀䏔㳅;->䪂㗫䣞㞅(Ljava/lang/String;Ljava/lang/Boolean;)Z. Assuming maxiumum ambiguity.
13:37:31.962 WARN  InvokeOp     - Attempting to execute local method without implementation: Lkik/䀆㚇䭰㛊㨴䏭㸞/䌺䦿䣅/䉀䏔㳅;->䪂㗫䣞㞅(Ljava/lang/String;Ljava/lang/Boolean;)Z. Assuming maxiumum ambiguity.```

So that's two bugs I need to look into, just haven't had time lately.

I _would_ recommend dex-oracle since it looks like this obfuscation could be handled by it. My guess is it shouldn't require too much modification of one of the existing plugins to make this work. I can work with you and answer specific questions, but you'll have to do the heavy lifting.

I'll keep this open until I can sort out the two bugs. Thanks for the report.

**Comment by Rewtarded** [comment]
@CalebFenton 
Ah, Interesting, gotta hate those bugs. 

I'm replying here and if it needs to be moved to the issues on dex-oracle, i'll delete this reply and paste it over there.

I have set up and installed dex-oracle, but i'm having a little bit of an issue with the driver creating a zip folder in my user temp file.  I have all the right admin permissions, even tried to move the temp file directly on C:\. Still haven't found any solutions on google yet. Although, I stumbled upon a similar issue in a random project on github. It hinted that the error could be something other then the fact that i'm on Windows. See image below below. 

![image](https://cloud.githubusercontent.com/assets/20191494/16706152/08472648-456f-11e6-9552-c8c1edd1a156.png)

**Comment by CalebFenton** [comment]
I swear this stuff works on my machine :D

I fixed the bugs you see there for dex-oracle on Windows, and a few more that I found while testing with your apk. I was able get dex-oracle to run on the apk but only after making a slight change. Oracle creates a dex file which allows oracle to run any method with any parameters by merging a driver dex and the input dex. Merging was failing because your apk's dex is huge and has more than 65535 strings. 

When the original apk was compiled, it was compiled with a `dx` flag `--force-jumbo` which turns all the `const-string`s into `const-string/jumbo`s. The anti-skid code **didn't** use jumbo, which makes sense because it's a weird edge case and their code, but when oracle tried to merge the two files, it broke. So, I had to _manually replace every "const-string " with "const-string/jumbo "_, build a dex from the modified smali, and run dex-oracle on that. There's a spiffy new error message if this is detected which also describes the process.

If you look at the presentation at the bottom of dex-oracle, check out the plugin code, get an idea of how the thing works, you could probably very easily identify the string decryption "pattern" and make that into a plugin. I encourage you to not give up since you've already come pretty far. :)

If you find any more dex-oracle issues, please create issues on that project since it helps me track them better.

**Comment by CalebFenton** [comment]
The original bug you reported has been fixed in https://github.com/CalebFenton/simplify/commit/80b02088639792aaf5fc5d48277a4ac26832ccfd

The warning about attempting to execute local method without implementation is because the invocation target (object that actually has the method we want to call) is unknown. All that's known is the interface type, so the target resolves to the interface and it has no implementation. The error message should probably be a little more descriptive but I need to check some stuff before changing it.

The method now runs, but times out because it takes too long. Strings are getting decrypted during run time, but the method times out so the optimizer doesn't get a chance to make any changes. It might work if you bump up the timeout stuff (max address visits, max method time, etc).
