### ISSUE TITLE
Illegal Argument Exception

### ISSUE THREAD

**Issue by Sputuks3** [CalebFenton/simplify#52]
Exception in thread "main" java.lang.IllegalArgumentException: No implementation for Lo/aee;->?(Ljava/lang/Appendable;Ljava/lang/String;)V

APK SHA1: 8b2599665a85476bbcfcbf3218a07a84262dde80

**Comment by CalebFenton** [comment]
What command did you use to run simplify? What classes were you targeting?

**Comment by Sputuks3** [comment]
![image](https://cloud.githubusercontent.com/assets/1269084/17273930/234c363e-56fb-11e6-9ef5-24ce08452089.png)

**Comment by CalebFenton** [comment]
Ah, you're running it over the whole file. I see. There are two problems:

1.) InvokeOp is unable to determine the actual (non abstract) virtual target for the method so it falls back on the referenced (abstract) method. This causes a failure and should be handled more gracefully. It shouldn't just quit.

2.) The code does a lot of funny stuff with class loaders, threads, etc, basically stuff smalivm will never be able to emulate. You'll probably have better luck with https://github.com/CalebFenton/dex-oracle. It looks like there's a little bit of reflection obfuscation, but no encrypted strings. Other than that, it's just a lot of annoying remapping.

I'll keep this open until InvokeOp is less brittle in dealing with this.

**Comment by Sputuks3** [comment]
I checked the relevant class/method. It is an interface. Hence, no implementation.

**Comment by CalebFenton** [comment]
Correct. Here's a bit more detail. This is the method call:

```smali
invoke-virtual {v3, v6, v7}, Lo/aab;->ˊ(Ljava/lang/String;Ljava/lang/String;)V
```

From this, you know `v3` implements the `o.aab` interface, but you don't know exactly what type it is. This is the virtual target. Smalivm will look at the value in `v3` and try to determine it's actual class. If it doesn't know because `v3` is unknown, it'll fall back on the declared / referenced class. In this case, that's the interface.

If you trace back up (jump through some hoops), you'll find the object seems to be created here:

```smali
new-instance v0, Lo/aad;
invoke-direct {v0, v6, v5}, Lo/aad;-><init>(Ljava/lang/ClassLoader;Ljava/lang/String;)V
invoke-static {v0}, Ljava/security/AccessController;->doPrivileged(Ljava/security/PrivilegedAction;)Ljava/lang/Object;
move-result-object v5
```

The `o.aad` class implements `java.security.PrivilegedAction` and `v6` is the class loader and `v5` is the string `"o.aaf"`. The `o.aaf` class implements `o.aab` is is the proper class of the virtual target of the method that's failing to execute.

The problem is that a lot of the methods aren't considered safe and won't be executed, so a lot of the values that are returned are unknown. For example, the result type of `doPrivileged` is `java.lang.Object`, and that's all smalivm knows about that object.

This could _probably_ work if a few methods were emulated. Off the top of my head:

* `Ljava/lang/Class;->getClassLoader()Ljava/lang/ClassLoader;`
* `Ljava/security/AccessController;->doPrivileged(Ljava/security/PrivilegedAction;)Ljava/lang/Object;`
* `Ljava/lang/Class;->newInstance()Ljava/lang/Object;`
* `Ljava/lang/ClassLoader;->loadClass(Ljava/lang/String;)Ljava/lang/Class;`

The `getClassLoader` can probably just wrap around smalivm's `SmaliClassLoader` since it knows of all input smali classes. The rest don't look too tricky (read: technically impossible). I think it would be worth it, but I can't say when I'll be able to do it. You're welcome to try. :D

**Comment by Sputuks3** [comment]
So you are saying with device emulation via `dex-oracle` it would be possible to know run-time type information for safe reconstruction of code?

**Comment by CalebFenton** [comment]
In general, whenever there's a lot of tricky stuff to execute, dex-oracle may perform better because it executes code directly on the device. With smalivm, everything has to be implemented and working correctly.

In this case, I don't know if oracle would really give you a lot of useful deobfuscation. You'd want to look for patterns in smali that, if you had only the information that was in that pattern, and could execute a method and change the stuff matched by the pattern based on the return result. For example, "here's some code that decrypts a string, run the decryption method with the encrypted string, replace all the code with `const-string` ..".

Smalivm would give better results, but it's a bit of work to add implementations of the methods I mentioned above. I think it's worth doing, so I'll do it, but it might be a while before I get around to it.
