### ISSUE TITLE
Unpacking Question ?

### ISSUE THREAD

**Issue by idanr1986** [CalebFenton/simplify#55]
do you think i can use smallvm for unpacking android malware ? 
by dumping the input of dalvik.system.DexFile.loadDex() and java.lang.Runtime.load() ?

**Comment by CalebFenton** [comment]
Only if the packer is implemented entirely in Dalvik, which is highly unlikely. Much better to instrument a VM or real device. I.e. take the android source code, modify loadDex to save the dex file to /data/local or something, and use that.

**Comment by CalebFenton** [comment]
I should add that it's a pretty good idea to hook those methods and dump whatever you find. It's probably been done before but I've never looked into it.

It just wouldn't work for simplify because the file system is not virtualized, meaning any loading of packed Dex files simply wouldn't happen. native code is not executed. Other types of io such as networking are also not virtualized. It would be possible to visualize these things by adding emulated methods for certain api like opening a file or socket or something. It just hasn't been done yet.

**Comment by CalebFenton** [comment]
Closing the issue for now. Feel free to continue the discussion.
