### ISSUE TITLE
Support API 24 and 25

### ISSUE THREAD

**Issue by ikoz** [CalebFenton/simplify#57]
I recently attempted to simplify an app compiled against API 24; it was using `java.nio.HeapLongBuffer` which is a recent addition to the java framework.

As smalivm uses API 23 internally, it fails with this error, because it is missing this class.

```
Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Ltest/test;-><init>([Ljava/lang/String;)V, op=invoke-virtual {r4, r6}, Ljava/nio/LongBuffer;->put(J)Ljava/nio/LongBuffer;} and was not handled. This could be a bug in smalivm.
Exception: java.lang.RuntimeException: Can't find Smali file for Ljava/nio/HeapLongBuffer;
```

This issue is created so that work towards supporting newer frameworks is tracked.

**Comment by ikoz** [comment]
I attempted to introduce support for API 24 and 25, by generating smali files for those frameworks in AndroidFrameworkSmali, a project included in smalivm as a submodule: https://github.com/CalebFenton/AndroidFrameworkSmali/pull/1

After the smali framework files are generated, the following steps need to be done (pretty undocumented, thanks @CalebFenton  for the help) 

1. Generate a framework_classes.cfg file for the framework

    This is done by running org.cf.smalivm.dex.FrameworkCacheBuilder in a IntelliJ environment (not from the Jar). It creates a cfg file referencing the location of the new framework. This cfg file needs to replace the original.

2. Generate a immutable_classes.cfg for the framework. 

    This seems to be a manual process, unsure how to do it for a specific framework. The existing cfg seems to be unrelated to the android-23 classes currently supported. I tried grepping for final classes, got somewhere, not sure if all is correct.

3. Generate a framework jar file for the framework using `org.cf.smalivm.dex.FrameworkJarBuilder`. 

    This uses the mentioned cfg file to create a jar and also has to be run through IntelliJ.

I did these steps for API 25, API 24 and even API 23 which currently exists. Unfortunately the following errors were observed:

1. For API 24 and 25, apparently SmaliClassLoader cannot generate valid classes. Things fail with the following message at runtime. Almost every test fails.

    ```
Exception in thread "main" java.lang.ClassFormatError: Method onProvideKeyboardShortcuts in class android/view/Window$Callback has illegal modifiers: 0x1
    ```

2. For API 23 fewer test fail; those that fail with the following:

    ```
java.lang.NullPointerException
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:537)
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:529)
	at org.jf.dexlib2.analysis.MethodAnalyzer.buildInstructionList(MethodAnalyzer.java:519)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:127)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:281)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:111)
	at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:152)
	at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
    ```

Proposals for next steps:

1. Document a reliable process to recreate cfg and jar files for the existing android-23 smali files and have all tests pass. I think that would help a lot.

2. In several places in simplify code, `OpCodes.getDefault()` is called from dexlib2. This could be replaced with OpCodes.getApi(23) or 24, 25, depending on needs. The default is 20. Not sure if this will change much.

**Comment by CalebFenton** [comment]
Thanks a ton for the well written writeup of the issues!

I agree this process should be more documented and in general easier to do and understand. It might work well as a Gradle task. As for including multiple frameworks, as long as Android frameworks continue to be backwards compatible, I think we can get away with just having one, especially because it really increases the size of the repo.

**Comment by unoexperto** [comment]
@CalebFenton Could you please release version for API 25 ?

**Comment by CalebFenton** [comment]
The reference API has been updated to 25. Thanks @ikoz for doing the heavy lifting of getting the smali.

Recent commits (including https://github.com/CalebFenton/simplify/commit/c195a49ac633668c2c13062b87d74425ae4d6c11) should help address this. The process is a little easier to understand. There's a new Gradle task: `updateReferenceFramework` and cache and jar building has been consolidated. I'm not super interested in adding tests myself since most of the work is done by ClassBuilder, which is and should be tested.

I'm not too worried about Opcode APIs because most Android APIs do not actually add new opcodes and I feel we can rely on dexlib to always be able to handle the newest opcodes without being explicit. I could be wrong, but this is what I understand having looked at the code a bit.

Except for `immutable_classes.cfg`, other configuration files are very much manually curated. The immutable classes are generated from an artifact [which is not part of the repo](http://stackoverflow.com/a/30197491), but it _should_ be updated from time to time (thanks for reminding me). The main benefit is slight speed and memory improvements since classes marked as immutable are not cloned and stored in each new execution context.

**Comment by CalebFenton** [comment]
Closing this and spawned a new issue based on discussion.
