### ISSUE TITLE
Problem with example-obfuscated

### ISSUE THREAD

**Issue by maxben14** [CalebFenton/simplify#68]
[log.txt](https://github.com/CalebFenton/simplify/files/902717/log.txt)

I try simplify on example-obfuskated but i get error and exception when simplify working.

```
Executing: Lorg/cf/obfuscated/XORCrypt;->decode(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
Aborting execution; exception: org.cf.smalivm.MaxAddressVisitsExceededException: Exceeded max address visits @11 ExecutionNode{signature=Lorg/cf/obfuscated/XORCrypt;->decode(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;, op=array-length r5, r0} in Lorg/cf/obfuscated/XORCrypt;->decode(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
Skipping Lorg/cf/obfuscated/XORCrypt;->decode(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
Executing: Lorg/cf/obfuscated/XORCrypt;->encode(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
Aborting execution; exception: org.cf.smalivm.MaxAddressVisitsExceededException: Exceeded max address visits @10 ExecutionNode{signature=Lorg/cf/obfuscated/XORCrypt;->encode(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;, op=array-length r4, r0} in Lorg/cf/obfuscated/XORCrypt;->encode(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
Skipping Lorg/cf/obfuscated/XORCrypt;->encode(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
```
After this excepion in function decode i don't stop simplify. 
Do I understand correctly that after excluding any one, should I stop the program?
Next, I see the looping of the program
```
16: 38: 16.905 WARN InvokeOp - org.cf.smalivm.MaxCallDepthExceededException: Exceeded max call depth in Landroid/support/v4/app/Fragment;->performPause()
```
In the system class android / support.
Why is the program trying to improve the system classes, how to make it miss them?

**Comment by CalebFenton** [comment]
The reason I like the obfuscated-example is that it's realistic, and normally when you see exceptions like that, there may be a good reason for it. In this case, there is. 'Exceeded max address visits' means that Simplify executed the same address too many times and assumes it's in a loop that will never stop. This can happen all the time. It's called the Halting Problem. In this specific case, it's because there's a loop that's dependent on some method argument, but since the method is being executed by itself, all of the arguments are unknown. This means Simplify is trying to execute something like `while (??) { doStuff(); }`. It'll try for a while then give up if the loop is never stopped. You could say the predicate is opaque due to argument ambiguity.

The second thing you mention is a warning and it's for the  same reason. Imagine something like this:
```java
static doStuff(int loopTimes) {
  while (loopTimes-- > 0) { doStuff(loopTimes); }
}```

Since simplify doesn't know the value of `loopTimes` it'll try for a while but if the call stack gets too deep (as it quickly will in this example) or if any particular address is executed too many times (as in the previous example) then it bails. This is an unsolvable problem, like straight up impossible, and these are just common work-arounds.

For android support classes, and in general, it's a good idea to use `-et` as "exclude types". In your case, `-et android/support` would probably work fine.

**Comment by CalebFenton** [comment]
Feel free to re-open if you still have an issue.

**Comment by maxben14** [comment]
https://github.com/CalebFenton/simplify/issues/70 I have problem yet. Do you see my apk file ?13.04.2017, 18:27, "Caleb Fenton" <notifications@github.com>:Feel free to re-open if you still have an issue.
