### ISSUE TITLE
Smalivm throws weird exceptions

### ISSUE THREAD

**Issue by voider1** [CalebFenton/simplify#92]
I was trying to use Smalivm and I followed your instructions on building it, now I'm getting the following error:

```
java.lang.RuntimeException: Error loading class definition: Landroid/icu/text/MessagePatternUtil;
	at org.cf.smalivm.type.ClassManager.parseClass(ClassManager.java:168)
	at org.cf.smalivm.type.ClassManager.parseClassIfNecessary(ClassManager.java:187)
	at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:120)
	at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:139)
	at org.cf.smalivm.type.ClassManager.getVirtualClass(ClassManager.java:113)
	at org.cf.smalivm.dex.SmaliClassLoader.findClass(SmaliClassLoader.java:92)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.cf.smalivm.context.ClonerFactory.build(ClonerFactory.java:57)
	at org.cf.smalivm.context.ExecutionContext.<init>(ExecutionContext.java:39)
	at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:173)
	at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:164)
	at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:160)
	at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:151)
	at Main.run(Main.java:26)
	at Main.main(Main.java:17)
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
	at org.cf.smalivm.dex.SmaliParser.parse(SmaliParser.java:69)
	at org.cf.smalivm.type.ClassManager.parseClass(ClassManager.java:165)
	... 15 more
```

My code looks like (it's Kotlin):

```kotlin
import org.cf.smalivm.VirtualMachineFactory

fun main(args: Array<String>) {
    val dex = "classes.dex"
    val methodSignature = "Lfsdfsdf/gsdsfsf/gjhghjg/lbljhkjblkjblkjblkj/accompanyingasfasfasfasfafa;->absorbasfasfasfasfafa(Ljava/lang/String;)Ljava/lang/String;"
    val arg = "\u001AT\u001FH\u0014S\u001F\u0014\u001AJ\u000B\u0014\u001AY\u000FS\u0014TU{?~$~>l2y>e:~6s5"

    val vmFactory = VirtualMachineFactory()
    val vm = vmFactory.build(dex)
    val ectx = vm.spawnRootContext(methodSignature)
    val mState = ectx.methodState
    mState.assignParameter(0, arg, "Ljava/lang/String")

    vm.execute(methodSignature, ectx)
}
```

This is the Java equivalent which gives me the same error:

```java
import org.cf.smalivm.VirtualMachine;
import org.cf.smalivm.VirtualMachineException;
import org.cf.smalivm.VirtualMachineFactory;
import org.cf.smalivm.context.ExecutionContext;
import org.cf.smalivm.context.ExecutionGraph;
import org.cf.smalivm.context.MethodState;

import java.io.IOException;

public class Main {
    final static String dexPath = "classes.dex";
    final static String methodSignature = "Lfsdfsdf/gsdsfsf/gjhghjg/lbljhkjblkjblkjblkj/accompanyingasfasfasfasfafa;->absorbasfasfasfasfafa(Ljava/lang/String;)Ljava/lang/String;";
    final static String arg = "\u001AT\u001FH\u0014S\u001F\u0014\u001AJ\u000B\u0014\u001AY\u000FS\u0014TU{?~$~>l2y>e:~6s5";

    public static void main(String[] args) {
        try {
            run();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static void run() throws IOException, VirtualMachineException {
        VirtualMachineFactory vmFactory = new VirtualMachineFactory();
        VirtualMachine vm = vmFactory.build(dexPath);
        ExecutionContext ectx = vm.spawnRootContext(methodSignature);
        MethodState mState = ectx.getMethodState();
        mState.assignParameter(0, arg, "Ljava/lang/String;");
        ExecutionGraph graph = vm.execute(methodSignature, ectx);
        System.out.println("Done!");
    }
}
```

**Comment by CalebFenton** [comment]
Thanks for the detailed error report -- can you share the classes.dex hash? It's hard to reproduce without the full setup. Also, personal note, I'm keen to help anyone using smalivm as a library, so I appreciate the error reports.

The error is saying that the class manager can't find `Landroid/icu/text/MessagePatternUtil;`. This suggests that maybe you didn't do a recursive clone. You should have a bunch of files in `smalivm/src/main/resources/framework/smali/android-25`, e.g.:

```
╭─caleb@haxcalibur  ~/repos/simplify/smalivm/src/main/resources ‹ruby-2.3.0› ‹master*›
╰─$ find . | grep MessagePatternUtil.smali
./framework/smali/android-25/android/icu/text/MessagePatternUtil.smali
```

Further, you should be able to run `gradle test` in either Simplify root or in smalivm subdirectory. If this passes, then you did do a recursive clone and there's some other problem.

**Comment by voider1** [comment]
Thanks for responding so promptly, I indeed didn't clone it recursively! After doing that I got another error:

```
Exception in thread "main" org.cf.smalivm.MaxAddressVisitsExceededException: Exceeded max address visits @37 ExecutionNode{signature=Lfsdfsdf/gsdsfsf/gjhghjg/lbljhkjblkjblkjblkj/accompanyingasfasfasfasfafa;->absorbasfasfasfasfafa(Ljava/lang/String;)Ljava/lang/String;, op=new-instance r0, Ljava/lang/String;, @=37} in Lfsdfsdf/gsdsfsf/gjhghjg/lbljhkjblkjblkjblkj/accompanyingasfasfasfasfafa;->absorbasfasfasfasfafa(Ljava/lang/String;)Ljava/lang/String;
	at org.cf.smalivm.MethodExecutor.checkMaxVisits(MethodExecutor.java:99)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:60)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:72)
	at MainKt.main(main.kt:14)
```

**Comment by CalebFenton** [comment]
The "max" errors are ways of dealing with the unsolvable [Halting problem](https://en.wikipedia.org/wiki/Halting_problem).

Basically, it's impossible to know if a loop or recursion has a reachable terminating condition. This can happen with `while (some_unkown_variable) { do_stuff(); }`. The `do_stuff();` invocation would eventually throw a `MaxAddressVisitsExceededException`.

You can try raising the limit to something really high and seeing if it finishes. This won't help and there's literally no solution if there are loops with unknown predicates. You can modify the code, execute something else, or try dex-oracle.

I'd be able to tell you more if I had the hash of the file you're trying to execute.

**Comment by voider1** [comment]
I see, that's a problem for sure. The APK I'm using this with is Android malware located [here](https://koodous.com/apks/1979d60ba17434d7b4b5403c7fd005d303831b1a584ea2bed89cfec0b45bd5c2). I think you can figure out what code I'm trying to run from looking at my code. I'll also try to raise the limit and see how this affects Smalivm.

**Comment by CalebFenton** [comment]
I understand what code you're trying to run.

The problem isn't with that line, specifically. The problem is that line gets executed too many times, probably because it's within the body of a loop which doesn't seem to terminate. When I investigate, I'll try and determine the structure and predicate of this loop. It could span multiple functions.

It's a common problem with this type of analysis. Unless it's being exacerbated by a bug in simplify, or there's a possible enhancement, there's probably nothing to be done on this front.

**Comment by voider1** [comment]
If the loop stops at a certain point, which it does, we should be possible to emulate it. I don't know if I succeeded in raising the limit, even though I've raised it through the builder, it seems to stop just as fast as a significant lower limit. Thoughts?

**Comment by CalebFenton** [comment]
Strictly speaking, smalivm isn't a true emulator. Some values are ambiguous, and if a branch condition includes an ambiguous (`UnknownValue`) value, all possible execution paths are taken. Consider this:

```
do {
    String s =  "hello, world!";
    System.out.println(s);
} while (readBooleanFromFileSystem());
```

The loop predicate is `readBooleanFromFileSystem()`. Smalivm won't know what the value is if it's read from the file system (or network, for that matter). Instead, at every loop, it'll take both execution paths -- continue the loop, exit the loop. This will never exit, and there's a good chance smalivm would abort at the `String s  = ...` line.

It isn't possible to know if the loop would ever exit with static analysis. It may be another thread, another app, or something else which modifies the filesystem to make it stop. Further, any operation with some known value and an unknown value results in an unknown value, e.g. `5 + UnknownValue = UnknownValue`. It's very likely that there's a loop predicate which has been tainted by an unknown value. It's most often an instance member variable since those depend a lot on execution order and context. I just looked at malware recently which populates some arrays used for string decryption when the app's `onCreate()` method is called. If you try to call the string decryption method before that `onCreate()` method is called, you get null pointer exceptions.

I'd want to look into this to figure out if what you're trying to do is possible with the current API. It may be clunky, but if it's possible and a reasonable use case, it would suggest a reasonable direction for improvement.

**Comment by voider1** [comment]
One idea I had was to make Smalivm more like [Unicorn Engine](http://www.unicorn-engine.org/). In UC you can initialize registers and the stack from you code. What if we could do the same thing with Smalivm? There are going to be some major changes to the API and internals of Smalivm, but it's for the better, I think. Being able to set the values which are needed for executing the smali would be a huge step forward.

**Comment by CalebFenton** [comment]
You can already set static fields, initialize instances, and can _probably_ easily implement setting instance fields.

Implementing Unicorn-style execution would be much easier than what smalivm does. It bends over backwards to make sure things work when values aren't known. Of course, the trade off is requiring the user to initialize static and instance members and provide concrete method arguments. It may _also_ need android lifecycle aware method order execution.

However, the main problem you'll find is that almost nothing will ever execute because so much relies on I/O or on accessing insecure APIs. Right now, this is not much of a problem because the methods just return UnknownValues if they're not whitelisted, and methods can even be called without knowing all the arguments, and really complex and native methods are usually reflected by the emulating JVM.

Can you think of a non-trivial example code that would execute using unicorn-style execution that smalivm doesn't already handle?
